version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    env_file:
      - .env.dev
    networks:
      - backend

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    depends_on:
      - mongodb
    networks:
      - backend
    ports:
      - "8000:8081"
    env_file:
      - .env.dev

volumes:
  mongodb_data:

networks:
  backend:
    driver: bridge

